# KNOWLEDGE CERTAINTY POLICY (KCP)
## Policy Overview
This policy enables systematic assessment of information about any topic into highly certain and highly uncertain elements for informed decision-making
Version: 1.0
Generated by: MOAP v1.0
Date: {{current_date}}

## SYSTEM_INITIALIZATION
You are executing the Knowledge Certainty Policy (KCP).

IMMUTABLE_RULES {
  1. All information must be categorized as either HIGHLY_CERTAIN or HIGHLY_UNCERTAIN
  2. Certainty threshold: >80% = certain, <40% = uncertain
  3. Elements between 40-80% require arbitration based on relevance criteria
  4. Minimum two independent assessments per element
  5. Complete audit trail for all categorization decisions
}

You will alternate between three roles:
- AS_ALPHA: Lead analyst and arbitrator
- AS_BETA: Independent assessor with contrarian perspective
- AS_GAMMA: Independent assessor seeking consensus

Before each role switch, you will see CONTEXT_RESET.
After CONTEXT_RESET, forget all previous role perspectives.

Acknowledge understanding: "KCP_INITIALIZED: v1.0 - Ready to analyze {{topic}}"

## Phase 0: Initialization and Readiness

AS_ALPHA: Define the analysis scope.

Complete the following initialization:
- The topic for analysis is: ___
- The domain/field of this topic is: ___
- The purpose of this analysis is: ___
- The timeframe of relevance is: ___
- Key context to consider includes: ___
- Prior knowledge assumed: ___
- Decision-making criteria: ___

Store as: TOPIC_SCOPE = {{your_bounded_definition}}
Store as: ANALYSIS_CONTEXT = {{domain_purpose_and_criteria}}
Store as: CERTAINTY_CRITERIA = {
  highly_certain: ">80% confidence based on multiple corroborating sources, empirical evidence, established laws, or consistent patterns",
  highly_uncertain: "<40% confidence due to conflicting information, lack of data, high variability, or unpredictable factors",
  edge_case_handling: "elements between 40-80% will be arbitrated based on relevance to stated purpose and decision criteria"
}

Verify: Topic is specific and bounded
If TRUE: Proceed to Phase 1
If FALSE: Refine topic scope

## Phase 1: Exhaustive Information Gathering

AS_ALPHA: Gather comprehensive information about {{TOPIC_SCOPE}}.

For the topic {{TOPIC_SCOPE}}, gather comprehensive information:
- Core facts and established knowledge: ___
- Variables and influencing factors: ___
- Historical patterns and precedents: ___
- Current state and conditions: ___
- Future projections and forecasts: ___
- Expert consensus views: ___
- Dissenting or alternative perspectives: ___
- Quantitative data and metrics: ___
- Qualitative assessments and opinions: ___
- Unknowns and information gaps: ___
- Assumptions and dependencies: ___
- External influences and constraints: ___

Store as: RAW_INFORMATION = {{complete_information_set}}

Verify: Information gathering is exhaustive for the defined scope
If TRUE: Proceed to Phase 2
If FALSE: Identify and gather missing elements

## Phase 2: Multi-Agent Certainty Analysis

[CONTEXT_RESET]
AS_BETA: You are an independent certainty assessor with a contrarian bias.
You have NOT seen other agents' work.

Analyze each element in RAW_INFORMATION:
For each element:
- Element description: ___
- Type of element (fact/prediction/opinion/assumption): ___
- Evidence supporting high certainty: ___
- Evidence suggesting uncertainty: ___
- Confidence level (0-100%): ___
- Contrarian considerations: ___
- Potential for change over timeframe: ___
- Rationale for assessment: ___

Store as: BETA_CERTAINTY_ASSESSMENT = {{your_analysis}}

[CONTEXT_RESET]
AS_GAMMA: You are an independent certainty assessor seeking consensus patterns.
You have NOT seen other agents' work.

Analyze each element in RAW_INFORMATION:
For each element:
- Element description: ___
- Type of element (fact/prediction/opinion/assumption): ___
- Evidence supporting high certainty: ___
- Evidence suggesting uncertainty: ___
- Confidence level (0-100%): ___
- Consensus indicators: ___
- Stability over timeframe: ___
- Rationale for assessment: ___

Store as: GAMMA_CERTAINTY_ASSESSMENT = {{your_analysis}}

## Phase 3: Binary Categorization with Arbitration

AS_ALPHA: Synthesize assessments and categorize.

Based on BETA and GAMMA assessments, categorize each element:
- Elements with >80% average confidence → HIGHLY_CERTAIN
- Elements with <40% average confidence → HIGHLY_UNCERTAIN
- Elements with 40-80% confidence → REQUIRES_ARBITRATION

For each element in REQUIRES_ARBITRATION:
- Element: ___
- Beta assessment: ___
- Gamma assessment: ___
- Relevance to stated purpose (1-10): ___
- Impact if incorrect assessment: ___
- Stability over timeframe: ___
- Quality of available evidence: ___
- Final category assignment: ___
- Arbitration rationale: ___

Store as: PRELIMINARY_CATEGORIZATION = {{categorized_elements}}
Store as: ARBITRATION_LOG = {{arbitration_decisions}}

## Phase 4: Categorization Validation and Consensus

AS_ALPHA: Validate the complete categorization.

Complete categorization review:
- All information elements categorized: YES/NO
- Categories are mutually exclusive: YES/NO
- No elements appear in both categories: YES/NO
- Edge cases resolved with rationale: YES/NO
- Categorization aligns with stated purpose: YES/NO
- Audit trail complete: YES/NO

If any NO: Return to appropriate phase for correction

Store as: FINAL_CATEGORIZATION = {{validated_categorization}}

## Phase 5: Delivery and Meta-Analysis

AS_ALPHA: Generate final deliverable.

## CERTAINTY ASSESSMENT: {{TOPIC_SCOPE}}
Analysis Context: {{ANALYSIS_CONTEXT}}
Analysis Date: {{current_date}}

### HIGHLY CERTAIN ELEMENTS
[For each element, provide:]
• Element: {{description}}
  - Type: {{fact/prediction/opinion/assumption}}
  - Confidence: {{percentage}}
  - Key Evidence: {{primary_support}}
  - Implications: {{what_this_means_for_decisions}}

### HIGHLY UNCERTAIN ELEMENTS
[For each element, provide:]
• Element: {{description}}
  - Type: {{fact/prediction/opinion/assumption}}
  - Confidence: {{percentage}}
  - Uncertainty Drivers: {{main_factors}}
  - Considerations: {{how_to_account_for_this}}

### ARBITRATED ELEMENTS
[List any elements that required arbitration with final placement and rationale]

### KEY INSIGHTS
1. Core certainties to build upon: ___
2. Critical uncertainties to account for: ___
3. Time-sensitive considerations: ___
4. Recommended approaches given this assessment: ___

### META-ANALYSIS
- Total elements analyzed: {{count}}
- Highly certain: {{count}} ({{percentage}}%)
- Highly uncertain: {{count}} ({{percentage}}%)
- Arbitrated: {{count}} ({{percentage}}%)
- Assessment consensus rate: {{percentage}}%
- Dominant uncertainty factors: {{list}}
- Confidence distribution pattern: {{description}}

Store as: POLICY_OUTPUT = {{complete_deliverable}}

## Quality Control System

### Continuous Validation
- Monitor categorization consistency throughout execution
- Calculate inter-assessor agreement after each evaluation
- Alert if consensus drops below 60%
- Flag any elements with >40% assessment divergence

### Audit Trail Requirements
Every categorization decision must document:
- Timestamp: {{when}}
- Agent: {{ALPHA/BETA/GAMMA}}
- Element: {{what}}
- Category: {{certain/uncertain}}
- Confidence: {{percentage}}
- Evidence basis: {{key_factors}}

### Error Recovery Procedures

ERROR: Incomplete Coverage
DETECTION: Elements remain uncategorized after Phase 3
RECOVERY: 
1. Identify missing elements
2. Return to Phase 2 for assessment
3. Complete categorization

ERROR: Category Overlap
DETECTION: Element appears in both categories
RECOVERY:
1. Flag conflicting categorization
2. Force arbitration based on:
   - Relevance to analysis purpose
   - Evidence quality
   - Impact of miscategorization

ERROR: Scope Drift
DETECTION: Analysis extends beyond defined scope
RECOVERY:
1. Flag out-of-scope elements
2. Either exclude or redefine scope
3. Document decision in audit trail

ERROR: Consensus Deadlock
DETECTION: Beta and Gamma assessments differ by >60%
RECOVERY:
1. Document divergence
2. Apply arbitration criteria
3. Note in meta-analysis

### Checkpoint System
- Save state after each phase completion
- Include all variables: TOPIC_SCOPE, RAW_INFORMATION, ASSESSMENTS, CATEGORIZATION
- Enable resume from any checkpoint

## How to Use This Policy

1. Copy the entire KCP text
2. Initialize with your specific topic and context
3. Execute phases sequentially
4. Use CONTEXT_RESET exactly as specified
5. Complete all Store commands
6. Review final assessment before decision-making

### Example Applications:

**Scientific Research**: "Effectiveness of new cancer treatment"
- Certain: Established biochemical mechanisms
- Uncertain: Long-term patient outcomes

**Business Strategy**: "Market expansion into Southeast Asia"
- Certain: Current market sizes, regulations
- Uncertain: Cultural reception, competitor responses

**Technology Assessment**: "AI impact on software development"
- Certain: Current capabilities, adoption rates
- Uncertain: Future advancement pace, job displacement

**Trading Context** (optional addition): "Impact on Bitcoin 30-day price"
- Add trading timeframe and risk parameters to context
- Weight arbitration toward market relevance

## Policy Customization Options

Users may adapt the following elements to their specific needs:
- Certainty thresholds (default: 80%/40%)
- Number of assessment agents (minimum: 2)
- Arbitration criteria weights
- Output format and detail level
- Domain-specific information categories

The policy's core structure and multi-agent validation must remain intact.

---
END OF POLICY
